export const BAIRROS_SP = [
  { value: "butanta", label: "Butantã" },
  { value: "pinheiros", label: "Pinheiros" },
  { value: "vila_mariana", label: "Vila Mariana" },
  { value: "moema", label: "Moema" },
  { value: "tatuape", label: "Tatuapé" },
  { value: "itaquera", label: "Itaquera" },
  { value: "santana", label: "Santana" },
  { value: "lapa", label: "Lapa" },
  { value: "consolacao", label: "Consolação" },
  { value: "perdizes", label: "Perdizes" },
  { value: "jabaquara", label: "Jabaquara" },
  { value: "ipiranga", label: "Ipiranga" },
  { value: "se", label: "Sé" },
  { value: "bela_vista", label: "Bela Vista" },
  { value: "liberdade", label: "Liberdade" },
  { value: "casa_verde", label: "Casa Verde" },
  { value: "mandaqui", label: "Mandaqui" },
  { value: "pirituba", label: "Pirituba" },
  { value: "freguesia_do_o", label: "Freguesia do Ó" },
  { value: "barra_funda", label: "Barra Funda" },
  { value: "campo_belo", label: "Campo Belo" },
  { value: "campo_limpo", label: "Campo Limpo" },
  { value: "capao_redondo", label: "Capão Redondo" },
  { value: "santo_amaro", label: "Santo Amaro" },
  { value: "cidade_dutra", label: "Cidade Dutra" },
  { value: "grajau", label: "Grajaú" },
  { value: "parelheiros", label: "Parelheiros" },
  { value: "mboi_mirim", label: "M'Boi Mirim" },
  { value: "sao_mateus", label: "São Mateus" },
  { value: "sao_miguel_paulista", label: "São Miguel Paulista" },
  { value: "ermelino_matarazzo", label: "Ermelino Matarazzo" },
  { value: "guaianases", label: "Guaianases" },
  { value: "lajeado", label: "Lajeado" },
  { value: "penha", label: "Penha" },
  { value: "vila_prudente", label: "Vila Prudente" },
  { value: "sapopemba", label: "Sapopemba" },
  { value: "aricanduva", label: "Aricanduva" },
  { value: "carrao", label: "Carrão" },
  { value: "cidade_tiradentes", label: "Cidade Tiradentes" },
  { value: "brasilandia", label: "Brasilândia" },
  { value: "tucuruvi", label: "Tucuruvi" },
  { value: "jacana", label: "Jaçanã" },
  { value: "tremembe", label: "Tremembé" }
];

